import json
from google import genai
from flask import current_app

_MODEL = 'gemini-1.5-flash'


def _client():
    return genai.Client(api_key=current_app.config['GEMINI_API_KEY'])


def grade_answer(question, answer_text):
    """Grade a student answer. Returns dict with score, feedback, confidence."""
    if not answer_text or not answer_text.strip():
        return {'score': 0, 'feedback': 'No answer provided.', 'confidence': 'high'}

    prompt = (
        f"You are an exam grader. Grade the following student answer.\n"
        f"Question: {question.text}\n"
        f"Model Answer: {question.model_answer or 'Not provided'}\n"
        f"Rubric: {question.rubric or 'Not provided'}\n"
        f"Max Marks: {question.max_marks}\n"
        f"Student Answer: {answer_text}\n\n"
        f"Respond in this exact JSON format with no extra text:\n"
        f'{{\n'
        f'  "score": <number between 0 and {question.max_marks}>,\n'
        f'  "feedback": "<2-3 sentence explanation of what was correct, partially correct, and missing>",\n'
        f'  "confidence": "<high|medium|low>"\n'
        f'}}'
    )

    response = _client().models.generate_content(model=_MODEL, contents=prompt)
    result = _parse_json(response.text)
    result['score'] = max(0.0, min(float(result.get('score', 0)), question.max_marks))
    return result


def detect_ai_generated(answer_text):
    """Return 0-100 probability that the text was AI-generated."""
    if not answer_text or not answer_text.strip():
        return 0.0

    prompt = (
        "Analyze the following text and estimate the probability (0-100) that it was "
        "generated by an AI language model rather than written by a human student.\n\n"
        "Consider: unusual formality, lack of personal voice, very balanced structure, "
        "suspiciously comprehensive coverage for a timed exam, generic phrasing.\n\n"
        f"Text:\n{answer_text}\n\n"
        'Respond with only this JSON and no extra text: {"ai_probability": <integer 0-100>}'
    )

    response = _client().models.generate_content(model=_MODEL, contents=prompt)
    result = _parse_json(response.text)
    return float(result.get('ai_probability', 0))


def _parse_json(text):
    text = text.strip()
    if '```' in text:
        parts = text.split('```')
        text = parts[1] if len(parts) > 1 else text
        if text.startswith('json'):
            text = text[4:]
    return json.loads(text.strip())
